version: "3.9"

services:
  backend-go:
    build:
      context: ./back
      dockerfile: docker-go.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./back/go:/app
    environment:
      - GO_ENV=development

  backend-java:
    build:
      context: ./back
      dockerfile: docker-java.Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./back/java:/app
    environment:
      - JAVA_ENV=development