# Server settings
spring.application.name=java
server.port=8081
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.additional-paths=/app/src/main/java

# DB settings (Docker Compose 기준)
spring.datasource.url=jdbc:postgresql://db:5432/livecommerce
spring.datasource.username=user
spring.datasource.password=password

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml